config/routes.rb
Sso::Application.routes.draw do
  devise_for :users, :path => "sessions"
  
  root :to => "index#home"
  resources :tokens, :only => [:create, :destroy]
  resources :clients, :users
  match "/me" => "index#me"
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :manage, User, :id => user.id
    
    if user.is_admin?
      can :manage, :all
    else
      can :read, User
    end
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :users

  def unique_key(len)
    SecureRandom.base64(len).tr('+/=lIO0', 'pqrsxyz')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :client
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable      

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :roles, :roles_mask, :client_id
  
  easy_roles :roles_mask, :method => :bitmask

  # Constant variable storing roles in the system
  # Roles can't be edited, if  if you need to add a new role,
  # just append it to the end of the array
  ROLES_MASK = %w[user admin]
    
  # Get bitmask value of role, useful for where clauses
  def self.role_bitmask(role)
    2**ROLES_MASK.index(role)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = exception.message
    redirect_to root_url
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_filter :authenticate_user!, :defaults
  load_and_authorize_resource
  
  def index
  end
  
  def new
  end

  def edit
  end
  
  def show
  end
  
  def update
    @client.update_attributes(params[:client])
    @client.save
    flash[:success] = 'Client updated successful.'
    redirect_to clients_url
  end
  
  def create
    @client = Client.new(params[:client])
    @client.key = @client.unique_key(16)
    @client.secret = @client.unique_key(24)
    @client.save
    flash[:success] = 'Client added successful.'
    redirect_to clients_url
  end
  
  def destroy
    @client.destroy
    flash[:success] = 'Client deleted successful.'
    redirect_to clients_url
  end
  
  def defaults
    @title = "Client Applications"
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  before_filter :authenticate_user!, :except => :home
  
  def home
  end
  
  def me 
    @user = current_user
  end
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource :user
  
  def create   
    @user.reset_authentication_token!
    redirect_to edit_user_registration_path(@user)
  end
  
  def destroy
    @user.authentication_token = nil
    @user.save
    redirect_to edit_user_registration_path(@user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :defaults
  load_and_authorize_resource
  
  def index
    @users = User.paginate(:page => params[:page], :per_page => 10)
  end
  
  def new
  end

  def edit
  end
  
  def show
  end
  
  def update
    @user.update_attributes(params[:user])
    @user.save
    flash[:success] = 'User updated successful.'
    redirect_to users_url
  end
  
  def create
    User.new(params[:user]).save
    flash[:success] = 'User added successful.'
    redirect_to users_url
  end
  
  def destroy
    @user.destroy
    flash[:success] = 'User deleted successful.'
    redirect_to users_url
  end
  
  def defaults
    @title = "Registered User"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clients/_form.haml
= semantic_form_for @client do |f|
	= f.inputs :name, :website
	= f.submit :class => 'small blue nice button radius'

app/views/clients/edit.haml
.row			
	.twelve.columns
		= render :partial => 'form'

app/views/clients/index.haml
.row			
	.twelve.columns
		%table{:width => '100%'}
			%thead
				%th ID
				%th Name
				%th Website
				%th Authorization
				%th Created At
				%th Updated At
				%th Actions
			%tbody
				- @clients.each do |client|
					%tr
						%td= client.id
						%td= client.name
						%td= link_to client.website, client.website
						%td 
							key: 
							%b= client.key
							%br
							secret: 
							%b= client.secret
						%td= client.created_at.to_s(:short)
						%td= client.updated_at.to_s(:short)
						%td
							= link_to 'edit', edit_client_path(client)
							= link_to 'delete', client_path(client), :method => :delete, :confirm => "Are you sure you want to delete the client?"
		= link_to 'Create client', new_client_path, :class => 'small blue nice button radius'

app/views/clients/new.haml
.row			
	.twelve.columns
		= render :partial => 'form'

app/views/index/home.haml
.row
	.twelve.columns{:align => 'center'}
		\... so you are finally here
		- if current_user
			= current_user.email
	

app/views/index/me.haml
.row
	.twelve.columns
	  = @user.email
	  %br 
	    also you are 
	    = @user.roles

app/views/layouts/application.haml
!!!
%html
	%head
		%title SSO
		
		= csrf_meta_tags
		= javascript_include_tag "foundation"
		= javascript_include_tag "application"
		
		= stylesheet_link_tag "application"
	%body
		.container
			.row
				.four.columns.offset-by-eight{:align => 'right'}
					%ul.menu
						= render :partial => 'devise/shared/registration_items'
						= render :partial => 'devise/shared/login_items'
			- if @title
				.row
					.twelve.columns
						.panel
							%h2= @title						
			.row
				.twelve.columns
					- flash.each do |key, value|
						.alert-box{:class => key}
							= value
			= yield

app/views/users/edit.haml
.row			
	.twelve.columns
		= semantic_form_for @user do |f|
			= f.inputs :email, :client
			= f.input :roles, :as => :check_boxes, :collection => User::ROLES_MASK
			= f.submit :class => 'small blue nice button radius'

app/views/users/index.haml
.row			
	.twelve.columns
		%table{:width => '100%'}
			%thead
				%th ID
				%th Email
				%th Sign In Count
				%th Roles
				%th Refferrer
				%th Created At
				%th Updated At
				%th Actions
			%tbody
				- @users.each do |user|
					%tr
						%td= user.id
						%td= user.email
						%td= user.sign_in_count
						%td= user.roles
						%td
						
						%td= user.created_at.to_s(:short)
						%td= user.updated_at.to_s(:short)
						%td
							= link_to 'edit', edit_user_path(user)
							= link_to 'delete', user_path(user), :method => :delete, :confirm => "Are you sure you want to delete the user?"
		= link_to 'Create user', new_user_path, :class => 'small blue nice button radius'
		= will_paginate @users

app/views/users/new.haml
.row			
	.twelve.columns
		= semantic_form_for @user do |f|
			= f.inputs :email, :password, :password_confirmation, :client
			= f.input :roles, :as => :check_boxes, :collection => User::ROLES_MASK
			= f.submit :class => 'small blue nice button radius'